import same from './src/same';
import validAnagram from './src/valid-anagram';
import uniqueValues from './src/unique-values';
import maxSubArraySum from './src/max-subarray-sum';
import binarySearch from './src/binary-search';
import sameFrequency from './src/same-frequency';
import factorial from './src/factorial';
import bubbleSort from './src/sorting-algorithms/bubble-sort';
import selectionSort from './src/sorting-algorithms/selection-sort';
import insertionSort from './src/sorting-algorithms/insertion-sort';
import mergeSort from './src/sorting-algorithms/merge-sort';
import quickSort from './src/sorting-algorithms/quick-sort';
import radixSort from './src/sorting-algorithms/radix-sort';
import singlyLinkedList from './src/data-structures/singly-linked-list';
import doubleLinkedList from './src/data-structures/double-linked-list';
import stacks from './src/data-structures/stacks';
import binarySearchTree from './src/data-structures/binary-search-tree';
import binaryHeaps from './src/data-structures/binary-heaps';

// same();
// findIndex();
// validAnagram();
// uniqueValues();
// maxSubArraySum();
// binarySearch();
// sameFrequency();
// factorial();
// bubbleSort();
// selectionSort();
// insertionSort();
// mergeSort();
// quickSort();
// radixSort();
// singlyLinkedList()
// doubleLinkedList();
// stacks();
//binarySearchTree();
binaryHeaps();
